pkslow:
  jwt:
    secretKey: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    validityInMs: 86400000

server:
  port: 8080

spring:
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform_db_merge_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mybatis-plus:
    mapper-locations: classpath:/mappers/*.xml

    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: WLKCxm159357
      database: ${REDIS_DB:0}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms


neo4j:
  uri: bolt://127.0.0.1:7687
  username: neo4j
  password: 12345678


graph:
  limit:
    # 图谱构建最大层级深度 (对应 Excel 的列数 0-4)
    max-depth: 5
    # 单个图谱最大节点数量限制 (熔断保护)
    max-nodes: 2000



# MinIO配置 (新增)
minio:
  endpoint: http://8.152.220.164:9000  # MinIO服务地址
  access-key: 9eBv4Rt6                 # 访问密钥
  secret-key: 3a7W5Mz8                 # 秘密密钥
  bucket: homework-bucket              # 存储作业的桶


dify:
  api:
    url: http://localhost
    homeworkkey: test
    expkey: test
    Databasekey: test
    questiongenekey: test
    chatkey: test

cache:
  ttl:
    course-list-seconds: 300
    course-detail-seconds: 300
    homework-list-seconds: 300
    homework-detail-teacher-seconds: 300
    class-list-seconds: 300
    question-list-seconds: 300
